#!/bin/sh
MEMBERS=$(serf members |wc |awk '{ print $1; }')
MIN_MEMBERS=${MIN_MEMBERS:-3}

while [ "$MIN_MEMBERS" -gt "$MEMBERS" ] 
do
	sleep 5
	MEMBERS=$(serf members |wc |awk '{ print $1; }')
done

export IP=$(hostname -I | cut -f 1 -d ' ')
export LEADER=$(serf members|sort -k 2 | head -n 1 | cut -f 3 -d ' ' |cut -f 1 -d ':')
export SERVER=${SERVER:-nomad:4647}

#if [$IP==$LEADER] 
if [ -z "$WORKER" ]
then
	exec nomad agent -server -bind=$IP -data-dir /tmp -bootstrap-expect $MIN_MEMBERS -join $LEADER -retry-join $LEADER  >>/var/log/nomad.log 2>&1
else
	mkdir /etc/nomad
	echo -e "client {\n  options {\n \"driver.raw_exec.enablei\" = \"1i\"\n }\n}\n" > /etc/nomad/client.conf
	exec nomad agent -client -bind=$IP -data-dir /tmp -servers $SERVER -config /etc/nomad/client.conf >>/var/log/nomad.log 2>&1
fi
